Fixed `octokit/request-action@v2`, unable to find version `v2`
request-action@v2 gives error

Error: Unable to resolve action `octokit/request-action@v2`, unable to find version `v2`

changed from github-action@v2 to actions/github-script@v6